### ISSUE TITLE
Yargs.

### ISSUE THREAD

**Issue by jiyoungsin** [jiyoungsin/OSD_A1_Tool#11]
Can someone implement yargs? I have never used yargs before.

**Comment by trewest** [comment]
What exactly do you want to use yargs for? If you want to provide help context, we can generate a message like this if a user passes in -h or --help options:

```
Usage: cliCommand.sh [OPTION]... [FILE]
Command-line tool to consider if URLs are good, bad, or unknown.

  -v, --version    Print cliCommand version
  -j, --json       Output results to urls.json file
```

**Comment by jiyoungsin** [comment]
exactly, just like those commands.

**Comment by jiyoungsin** [comment]
@trewest If its okay with you can I use that text you wrote? I will be implementing yargs later today. Thank you for commenting on my issue.

**Comment by trewest** [comment]
That is the output of code that I wrote. Do you want to assign me and I can open a pull request? If not, you can use the text I wrote.

**Comment by jiyoungsin** [comment]
please! pull requests are welcome.

**Comment by jiyoungsin** [comment]
@trewest hey thanks for the PR. Im still confused on how getopt works. should I be downloading this getopt library?

**Comment by trewest** [comment]
getopt is a built-in bash command that lets you parse command-line options. This is more so just to accept the command line arguments you are using and provide additional help if necessary. The case block checks for options -v, -j, -h or long options --version, --json, --help. Since -j or --json is the only option that we can offer additional help, that is the only option that I give extended help on like so:

```
→ ./cliCommand.sh -j
Incorrect Usage: cliCommand.sh -j|--json [FILE]
```
```
→ ./cliCommand.sh --json fakefilename
Incorrect Usage: cliCommand.sh -j|--json [FILE]
```
If you wanted a way to track custom arguments by allowing the user to pass something like `--a=1`  we could use an associative array to store key-value pairs in but it could be dangerous to store all of the options that a user passes in.

Here is an example of what you could do (taken from the js examples for yargs):

-------------------------
**Code:**
```
declare -A argArray

for i in $*; do
        [[ ($i == *"--"*) && ($i == *"="*) ]] && {

                argArray[$(echo $i | cut -d "=" -f 1 | tr -d - )]=$(echo $i | cut -d "=" -f 2)
        }
done


if [ ${argArray[ships]+true} ] && [ ${argArray[distance]+true} ]
then

        if [ "${argArray[ships]}" -gt 3 ] && [ $(echo "${argArray[distance]} < 53.5") ]
        then
                echo 'Plunder more riffiwobbles!'
        else
                echo 'Retreat from the xupptumblers!'
        fi
fi
```
**Output:**
```
→ ./yargsTest.sh --ships=5 --distance=22
Plunder more riffiwobbles!
```
```
→ ./yargsTest.sh --ships=12 --distance=98.7
Retreat from the xupptumblers!
```
------------

The scripts stores keys by parsing command-line arguments and saving anything here: `--*=` as a key in the argArray and then saves whatever is here: `--key=*` as the value. Then if you wanted to make a decision based on the value of ships and distance, you would make sure that both keys exist in the array.

However, it probably makes more sense to only accept the options that your script supports.

**Comment by jiyoungsin** [comment]
Thank you for the explaination! I have yet to use yargs. This helped clarify what getopt is about.

**Comment by trewest** [comment]
Sure thing. Can you add the "hacktoberfest-accepted" label to my PR? :)
